#4. Extract and merge LR summary tables across samples
"""
This script extracts ligand–receptor (LR) interaction summaries from multiple
AnnData (.h5ad) objects generated by stLearn CCI analysis and combines them
into a single table.

Each input .h5ad file contains LR interaction statistics stored in: adata.uns["lr_summary"]

This table summarizes LR-level spatial interaction results, including metrics
such as the total number of spots, the number of spots with significant LR
scores, and cell-type interaction statistics.
"""

import os
os.environ["NUMBA_DISABLE_CACHE"] = "1"
import scanpy as sc
import pandas as pd

input_dir = r"path\to\h5ad_files"

all_dfs = []

for file in os.listdir(input_dir):
    if file.endswith(".h5ad") and file.startswith("Sig_Simple_Grid_"):
        file_path = os.path.join(input_dir, file)
        print(f"Processing {file}")
        adata = sc.read_h5ad(file_path)
        lr_summary = adata.uns["lr_summary"].copy()
        lr_summary = lr_summary.reset_index().rename(columns={"index": "LR"})
        name_part = file.replace("Sig_Simple_Grid_", "").replace(".h5ad", "")
        Sample = name_part
        Patient = name_part.split("_")[0]
        TimePoint = name_part.split("_")[1]
        lr_summary["Sample"] = Sample
        lr_summary["Patient"] = Patient
        lr_summary["TimePoint"] = TimePoint
        all_dfs.append(lr_summary)

bind_lr_summary = pd.concat(all_dfs, ignore_index=True)

bind_lr_summary.to_csv(
    os.path.join(input_dir, "All_LR_Summary.tsv"),
    sep="\t",
    index=False
)

print("Finished.")
